language: ruby
rvm:
  - 2.3.4
before_install:
  - nvm install node
  - npm install -g bower
install:
  - bundle install
  - bower install
before_script:
  - bundle exec middleman build
script:
  - ruby test.rb
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
