language:
  - node_js
  - ruby
rvm:
  - 2.5.1p57
before_install:
  - nvm install node
  - npm install -g bower
install:
  - bundle install
  - bower install
before_script:
  - bundle exec middleman build
script:
  - ruby test.rb
deploy:
  - bundle exec middleman deploy
# branches:
#   only:
#     - master
